### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by anowacki** [mantle-convection-constrained/terratools#43]
Examples we would like to include:

- [x] Read in file; make profile of T and plot (JP)
- [x] As above, but make a map of T or C fraction (JWa)
- [x] Plot cross section (AN) (#113)
- [x] Extract individual points (AN) (#113)
- [x] Use multiple lookup tables to calculate Vp, etc. from T and C (AW, FL)
- [x] 1D profile (JP) (#119; needs updating)
- [x] Add adiabat (JWa)
- [x] Convert flow to geographic; plot flow (JWo)
- [x] Spherical harmonic analysis (JP) (#125)

Please add others as needed.

For this we need:
- [x] An method to downloaded example files which can be hosted somewhere (#101, #116)
- [x] Example model files (JWa; JP)
- [ ] Example layer files

**Comment by jamespanton93** [comment]
I have made examples for reading data and plotting 1D profiles, but I will hold off committing them as they will probably benefit from having some example data accessible, rather than using internally generated files which produce funny looking profiles

**Comment by eejwa** [comment]
Reopening this issue as not all examples listed have been added yet.

**Comment by jwookey** [comment]
Oops, closed the wrong issue - sorry.

**Comment by anowacki** [comment]
Well done and thanks everyone!  We have ticked all but the single layer files off the list.  (As that isn't a blocker, we can wait for #106.)  Hence we can close this issue!
